### ISSUE TITLE
Script for Starting/Stopping Development Node

### ISSUE THREAD

**Issue by 4meta5** [web3garden/sunshine-node#35]
Something like this:

```
./target/release/node-template purge-chain --dev

USED_PORTS="$(lsof -i:9944)"
kill -9 "${USED_PORTS}"

./target/release/node-template --dev --port=9944
```

should be a bash script and should be placed in `scripts/`

**Comment by clearloop** [comment]
## pm2
> need extra installation

Have you tried `pm2`? we use [pm2][0] to manage our substrate nodes?

## systemd
> not easy to debug

And how about `systemd` in Linux or `sysadminctl` in OSX?

## scripts
> sometimes scripts are a mess

Or a signal `.pid` file, like the flutter server doing.

## cargo-cmd
> seems nice

This [cargo-cmd][1] looks nice, but long time not updating.

[0]: https://github.com/Unitech/pm2
[1]: https://github.com/danreeves/cargo-cmd

**Comment by 4meta5** [comment]
Abstract solution (2) sounds reasonable. 

To be fair, it's probably not worth it because this just isn't much of a bottleneck for me right now. Zsh remembers old commands so I usually just up arrow back to one of those four commands after I put them in the first time.

**Comment by dvc94ch** [comment]
mmh, don't like adding a node tool. I just checked, I have node/npm installed, but I wouldn't want to require people to have it installed.

**Comment by clearloop** [comment]
> mmh, don't like adding a node tool. I just checked, I have node/npm installed, but I wouldn't want to require people to have it installed.

Reasonable, what about use `nohup` to rise background process?

**Comment by 4meta5** [comment]
> mmh, don't like adding a node tool. I just checked, I have node/npm installed, but I wouldn't want to require people to have it installed.

Same, I agree, would be ideal to add `--daemon` flag to `node/src/command.rs`

**Comment by dvc94ch** [comment]
I'm not sure what the point is exactly. I have a terminal open where I run the node and another where I run the client

**Comment by 4meta5** [comment]
ye, this is issue is probably unnecessary. The friction introduced when starting/stopping a node is trivial relative to the other commands I have to use to operate stuff

Thanks for trying to help @clearloop but I'm going to close this one. Sorry for wasting your time :/

**Comment by clearloop** [comment]
> Thanks for trying to help @clearloop but I'm going to close this one. Sorry for wasting your time :/

It doesn't matter, actually, I'm thinking of the `bg` process problems for a long time LOL, hardly trying to re-write `pm2` in rust...
