### ISSUE TITLE
Bribery-Resistant Voting

### ISSUE THREAD

**Issue by 4meta5** [web3garden/sunshine-node#4]
Implement some privacy-protecting cryptography to hide voter's votes until time expires. Commit-reveal would be easy, but I kind of agree with [this](https://dbmsmusings.blogspot.com/2019/01/its-time-to-move-on-from-two-phase.html). Although, you could use bulletproofs and make the proof noninteractive. See [ZEXE](https://github.com/scipr-lab/zexe) and [Bellman](https://github.com/zkcrypto/bellman).

Also, see [zkSNARKs used in the context of Substrate](https://github.com/LayerXcom/zero-chain).

If this isn't implemented, voters have an incentive to wait until as late as possible -- so in the voting algorithms we would need to weight early voters more than late voters. However, parameterization is nontrivial -- probably use some sort of curve. It would be nice to have an alternative with constant rewards for all voters in proportion to the number of shares they have.

**Comment by AmarRSingh** [comment]
Upon further reading, I realized that the current implementation (as well as MolochDAO) is very naive with respect to security assumptions.

A snippet of the bribery-resistant smart contract voting scheme provided by **(1)** is:
1. A voter registers by putting cryptographic material, along with an attestation of its correctness, on the blockchain. *(registration occurs on Intel SGX, see **(3)** for coercion resistance)*
2. Users cast votes for a given candidate by submitting a ciphertext, the candidate name, and a zero-knowledge proof to the blockchain. They do so via an anonymous channel like Tor.
3. For each ballot, the EA tests if a ballot is a fake vote or a real one. If real, the EA outputs an additively homomorphic ciphertext with the encryption of 1. If fake, an encryption of 0. For each ballot, it also outputs a proof that the ciphertext and test were computed correctly. These can be checked by anyone
4. The sum of those ciphertexts is computed by everyone. For each candidate, the voting authority then gives the decryption of the sum. The sum is the number of honest votes for that candidate.

**(1)** [Bribery Resistant Voting Schemes for Smart Contracts](https://ethresear.ch/t/bribery-resistant-voting-schemes-for-smart-contracts/3354)
**(2)** [On-Chain Vote Buying and the Rise of Dark DAOs](http://hackingdistributed.com/2018/07/02/on-chain-vote-buying/)
**(3)** [Rust Intel SGX SDK](https://github.com/baidu/rust-sgx-sdk)

**Comment by 4meta5** [comment]
[Microsoft's Secure, Verifiable Voting Protocol](https://blogs.microsoft.com/on-the-issues/2019/05/06/protecting-democratic-elections-through-secure-verifiable-voting/) is worth imitating -- UI choices seem smart and allow verification of authenticity by any party (participating or non-participating if required.

The innovation isn't how they hide votes; it's just homomorphic encryption and then specialized computation on encrypted values (aggregation of votes). The real value add is the "ElectionGuard SDK" that facilitates audits -- it isn't technically difficult to implement, but it is a good idea.

**Comment by 4meta5** [comment]
[Forward-Secure Linkable Ring Signatures from Bilinear Maps](https://www.mdpi.com/2410-387X/2/4/35)

**Comment by 4meta5** [comment]
Two approaches that have caught my attention include [decred's incentivized mixnet](https://blog.decred.org/2019/08/28/Iterating-Privacy/) and [vvvote](https://stackedit.io/viewer#!url=https://raw.githubusercontent.com/pfefffer/vvvote/master/doc/protocol/protocol.md).
