### ISSUE TITLE
Is there any place we can chat about sunshine-node online?

### ISSUE THREAD

**Issue by clearloop** [web3garden/sunshine-node#53]
Hi team! 

I'm working at a company which is developing a substrate-based blockchain same as `sunshine-node`, and...I'm a fan of @dvc94ch because of `flutter-rs`, I guess we have some similar aspirations!! 

I'd like to contribute to `sunshine-node` when I'm free of everyday works, is there any place we can chat about it online like `flutter-rs`'s [gitter][0] 

[0]:https://gitter.im/flutter-rs/community

**Comment by 4meta5** [comment]
If you have questions, feel free to send them in this gitter room: https://gitter.im/sunshineprotocol/community

and I'll respond when I'm free, but now is probably a bit too early. I definitely want to encourage community engagement when we're ready, but things are so unstable right now that I don't want to waste your time :)

If you provide an email, I can email you when we're further along but we're still discovering our basic structure so, ye, it is early!

**Comment by clearloop** [comment]
> If you have questions, feel free to send them in this gitter room:
> https://gitter.im/sunshineprotocol/community

Thanks!

> It is early!

My company's substrate project is also at an early stage, and I just determined to develop substrate projects in the next few years of my life~

It's nice to see a project growing bigger and stronger from scratch, and I love creating products more than using products : )

**Comment by 4meta5** [comment]
> I just determined to develop substrate projects in the next few years of my life

Cool, me too!!

**Comment by clearloop** [comment]
@yangwao hey bro, have a look at this project~

`web3garden` is also trying to do some mobile works for `substrate`!

https://github.com/vue-polkadot/apps/issues/66

**Comment by yangwao** [comment]
Happy to see that we've met in issues! Let's work on something and reflect later 🍷
